version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "osha-interpretations-scraper"
s3_bucket = "mancomm-test-bucket"
s3_prefix = "osha-interpretations-scraper"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev MongoDbName=mancomm MaxInterpretations=100"
image_repositories = []
